spring.application.name=Reservation_api_project
spring.datasource.url=jdbc:mysql://localhost:3306/reservation
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정 (DB 테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 시크릿 키
jwt.secret=k6peybA7icZNu18a2J//Cs7DnBmsVVGJiHFVMPWOvAg=
# 45분
jwt.experation=2700000 